name: FireGods
main: me.mango.firegods.FireGods
version: b1
description: OPs can trail fire behind them like gods!
author: Mango
commands:
    fire:
      description: Toggles Fire God mode
      usage: /<command>