name: FireGods
main: me.mango.firegods.FireGods
version: b3
description: Lets admins trail fire behind them like gods!
author: Mango
commands:
    fire:
      description: Toggles Fire God mode
      usage: /<command>